import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import { Sidebar } from "./_components/sidebar"
import { cn } from "@/lib/utils"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "MLOps-Webapp",
    description: "Generated by create next app",
}

import React, { Suspense } from 'react';

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <head>
            <link rel="icon" href="/favicon.ico?v=2" type="image/x-icon" />
            </head>
            <body className={cn(inter.className,
                "flex h-full gap-x-20")}>
                <Suspense fallback={<div>Loading...</div>}>
                    <Sidebar />
                </Suspense>
                <main className="relative overflow-hidden">
                    {children}
                </main>
            </body>
        </html>
    )
}
