let data_analysis = [
    {
        id: 1,
        label: "DVC",
        src: "/stackicons/dvc.svg",
        alt: "DVC Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 2,
        label: "Kedro",
        src: "/stackicons/kedro.svg",
        alt: "Kedro Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 3,
        label: "MLflow",
        src: "/stackicons/mlflow.svg",
        alt: "MLflow Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
]

let experimentation = [
    {
        id: 1,
        label: "MLflow",
        src: "/stackicons/mlflow.svg",
        alt: "MLflow Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 2,
        label: "Kedro",
        src: "/stackicons/kedro.svg",
        alt: "Kedro Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
]

let feature_store = [
    {
        id: 1,
        label: "MLflow",
        src: "/stackicons/mlflow.svg",
        alt: "MLflow Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 2,
        label: "Kedro",
        src: "/stackicons/kedro.svg",
        alt: "Kedro Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
]

let code_repository = [
    {
        id: 1,
        label: "MLflow",
        src: "/stackicons/mlflow.svg",
        alt: "MLflow Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 2,
        label: "Kedro",
        src: "/stackicons/kedro.svg",
        alt: "Kedro Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
]

let ml_pipeline = [
    {
        id: 1,
        label: "MLflow",
        src: "/stackicons/mlflow.svg",
        alt: "MLflow Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 2,
        label: "Kedro",
        src: "/stackicons/kedro.svg",
        alt: "Kedro Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
]

let model_registry = [
    {
        id: 1,
        label: "MLflow",
        src: "/stackicons/mlflow.svg",
        alt: "MLflow Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 2,
        label: "Kedro",
        src: "/stackicons/kedro.svg",
        alt: "Kedro Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
]

let model_serving = [
    {
        id: 1,
        label: "MLflow",
        src: "/stackicons/mlflow.svg",
        alt: "MLflow Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 2,
        label: "Kedro",
        src: "/stackicons/kedro.svg",
        alt: "Kedro Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
]

let metadata_store = [
    {
        id: 1,
        label: "MLflow",
        src: "/stackicons/mlflow.svg",
        alt: "MLflow Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 2,
        label: "Kedro",
        src: "/stackicons/kedro.svg",
        alt: "Kedro Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
]

let model_monitoring = [
    {
        id: 1,
        label: "MLflow",
        src: "/stackicons/mlflow.svg",
        alt: "MLflow Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
    {
        id: 2,
        label: "Kedro",
        src: "/stackicons/kedro.svg",
        alt: "Kedro Icon",
        tag1:"Experiment tracking",
        tag2:"Data versioning",
        tag3:"Pipeline orchestration",
        description:"DVC is an open-source version control system for machine learning projects.",
        advantage1:"DVC is an open-source version control system for machine learning projects.",
        advantage2:"You want many options for remote storage of your data (S3, Minio, Google Cloud Storage, Google Drive, Azure Blob Storage, etc.)",
        advantage3:"You want to create pipelines and track your experiments.",
        disadvantage1:"You must use DVC alongside a Git repository to enable its versioning features.",
    },
]

module.exports = {
    data_analysis,
    experimentation,
    feature_store,
    code_repository,
    ml_pipeline,
    model_registry,
    model_serving,
    metadata_store,
    model_monitoring
}